apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: old-products
  labels:
    micro-old-products: old-products
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-old-products: old-products
  template:
    metadata:
      name: old-products
      labels:
        micro-old-products: old-products
    spec:
      containers:
      - name: old-products
        image: dongtu/kube-microservice:old-product-api-v1
        ports:
          - containerPort: 1081
      - name: old-productdb
        image: dongtu/kube-microservice:old-product-db-latest
        ports:
          - containerPort: 3309
---
apiVersion: v1
kind: Service
metadata:
  name: old-product-service
  labels:
    micro-old-products: old-products
spec:
  selector:
    micro-old-products: old-products
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
