apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-oldpro-api
  labels:
    micro-payment: payment-oldpro
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-payment: payment-oldpro
  template:
    metadata:
      name: payment-oldpro-api
      labels:
        micro-payment: payment-oldpro
    spec:
      containers:
      - name: payment-oldpro-api
        image: dongtu/kube-microservice:payment-oldpro-api-v2
        ports:
          - containerPort: 1085
      - name: payment-db
        image: dongtu/kube-microservice:payment-oldpro-db
        ports:
          - containerPort: 3309

---
apiVersion: v1
kind: Service
metadata:
  name: payment-oldpro-service
  labels:
    micro-payment: payment-oldpro
spec:
  selector:
    micro-payment: payment-oldpro
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
