apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment-api
  labels:
    micro-payment: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-payment: payment
  template:
    metadata:
      name: payment-api
      labels:
        micro-payment: payment
    spec:
      containers:
      - name: payment-api
        image: dongtu/kube-microservice:payment-api-v2
        ports:
          - containerPort: 1085
      - name: payment-db
        image: dongtu/kube-microservice:payment-db
        ports:
          - containerPort: 3309

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    micro-payment: payment
spec:
  selector:
    micro-payment: payment
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
