apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: products
  labels:
    micro-svc1: products
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-svc1: products
  template:
    metadata:
      name: products
      labels:
        micro-svc1: products
    spec:
      containers:
      - name: product-api
        image: dongtu/kube-microservice:product-api-v7
        ports:
          - containerPort: 1080
      - name: productdb
        image: dongtu/kube-microservice:productdb-latest
        ports:
          - containerPort: 3309

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    micro-svc1: products
spec:
  selector:
    micro-svc1: products
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
