apiVersion: v1

kind: Service

metadata:

  name: product-mysql

  labels:

    app: product-mysql

spec:

  ports:

  - port: 3306

    name: product-mysql

  clusterIP: None

  selector:

    app: product-mysql

---

apiVersion: apps/v1beta1

kind: StatefulSet

metadata:

  name: product-mysql

spec:

  serviceName: "product-mysql"

  replicas: 1

  template:

    metadata:

      labels:

        app: product-mysql

    spec:

      terminationGracePeriodSeconds: 10
      containers:

      - name: product-mysql

        image: dongtu/kube-microservice:productdb-latest

        ports:

        - containerPort: 3306

          name: product-mysql

        volumeMounts:

        - name: product-mysql-vol

          mountPath: /var/lib/mysql

  volumeClaimTemplates:

  - metadata:

      name: product-mysql-vol

    spec:

      accessModes: [ "ReadWriteOnce" ]

      resources:

        requests:

          storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: product-mysql-vol
  labels:
    type: local
spec:
  storageClassName: gp2
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
