apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    micro-messq: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-messq: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        micro-messq: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
          - containerPort: 5672
            name: queue-rw-port
          - containerPort: 15672
            name: queue-mgt-port
          - containerPort: 5671
            name: queue-ssl
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    micro-messq: rabbitmq
spec:
  selector:
    micro-messq: rabbitmq
  type: NodePort
  ports:
    - port: 5672
      name: queue-rw-port
      nodePort: 31234
    - port: 15672
      name: queue-mgt-port
      nodePort: 31606
    - port: 5671
      name: queue-ssl
      nodePort: 32718
