apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users-api
  labels:
    micro-users: users
spec:
  replicas: 1
  selector:
    matchLabels:
      micro-users: users
  template:
    metadata:
      name: users-api
      labels:
        micro-users: users
    spec:
      containers:
      - name: users-api
        image: dongtu/kube-microservice:users-api
        ports:
          - containerPort: 1084
      - name: users-db
        image: dongtu/kube-microservice:users-db-latest
        ports:
          - containerPort: 3309
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  labels:
    micro-users: users
spec:
  selector:
    micro-users: users
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

